name:                intensional-functions-examples
version:             0.1.0.0
github:              "zepalmer/intensional-functions-examples"
license:             BSD3
author:              "Zachary Palmer"
maintainer:          "zep_github@bahj.com"
copyright:           "2021-2022 Zachary Palmer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A set of examples demonstrating the use of intensional functions and algebraic structures.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zepalmer/intensional-functions-examples#readme>

dependencies:
- base >= 4.15 && < 5
- containers
- intensional-algebraic-structures

library:
  source-dirs: src

executables:
  intensional-functions-examples-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intensional-functions-examples

tests:
  intensional-functions-examples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intensional-functions-examples
    - HUnit
