name:                intensional-functions-closure-engine
version:             0.1.0.0
github:              "zepalmer/intensional-functions-closure-engine"
license:             BSD3
author:              "Zachary Palmer"
maintainer:          "zep_github@bahj.com"
copyright:           "2021-2022 Zachary Palmer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A library using intensional functions to define a flexible deductive closure engine.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zepalmer/intensional-functions-closure-engine#readme>

dependencies:
- base >= 4.15 && < 5
- containers
- intensional-algebraic-structures

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  {}
  # intensional-naive-subtype-closure:
  #   main:                Main.hs
  #   source-dirs:         apps/intensional-naive-subtype-closure
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - intensional-functions-examples

tests:
  intensional-functions-closure-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - intensional-functions-closure-engine
    - HUnit
