# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# NOTE: this should eventually be a GHC 9.0.1 resolver, but as of this writing
#       (2021-08-06), there are no LTS resolvers using 9.0.1.  Although we don't
#       use the stock compiler, it'd help to ensure that the packages are
#       compatible with our GHC.
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/0.yaml

# Using intensional functions GHC
# NOTE: This should eventually point to a publicly visible repository.
compiler: ghc-git-f179f9ab2dbb7ede6ba45d00aa45c3d8e74352dd-quick
compiler-repository: git.bahj.com:intensional-functions-ghc

# User packages to be built.
packages: ["."]

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
  - git: git.bahj.com:intensional-functions-lib
    commit: d0a420dbdbff415a3fa7a848c6ce00e9f7a46d08
